=== Configuration du plugin

Le plugin permet en configuration générale de paramétrer la fréquence du cron.

Il faut ajouter un équipement et sélectionner l'équipement Localisation et Trajets (geotrav) qui servira pour le calcul.

Ce plugin utilise une information venant du plugin Localisation et Trajets (geotrav) afin de réutiliser une localisation déjà existante.

Un autre paramètre est disponible pour paramétrer l'angle qu'on souhaite utiliser pour le calcul du coucher et lever du soleil uniquement (par défaut 90.58, ce qui est utilisé en général)

Le plugin apporte différentes informations, certaines sont calculées quotidiennement, d'autres sont rafraichit par le cron dédié.


Informations à rafraichissement quotidien (le calcul est fait à 3h du matin, sur démarrage de la box Jeedom ou sur sauvegarde de l'équipement) :

  - lever du soleil

  - coucher du soleil

  - durée de la journée (entre lever du soleil et coucher du soleil)

  - zenith du soleil

  - aube astronomique (lever du soleil -18°)

  - aube nautique (lever du soleil -12°)

  - aube civile (lever du soleil -6°)

  - crépuscule astronomique (lever du soleil +18°)

  - crépuscule nautique (lever du soleil +12°)

  - crépuscule civil (lever du soleil +6°)

Les informations restantes sont recalculées à la fréquence paramétrée sur la configuration plugin :

  - azimuth solaire

  - altitude solaire

  - phase du jour numérique

  - phase du jour texte

  Les valeurs de la phase du jour sont :

    - 0 : Nuit

    - 1 : Jour

    - 2 : Aube Civile

    - 3 : Aube Nautique

    - 4 : Aube Astronomique

    - 5 : Crépuscule Civil

    - 6 : Crépuscule Nautique

    - 7 : Crépuscule Astronomique
